version: '3'
services:
  bot:
    container_name: vilochnik-bot
    build: .
    environment:
      - DB_HOST=redis
      - DB_PORT=6379
    env_file:
      - token.env
  redis:
    container_name: redis
    image: redis:5.0.7-alpine
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 1'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
    volumes:
      - ./redisdata:/data
    ports:
      - "6379:6379"